server:
    port: 8001

spring: 
    datasource: 
        tomcat-jdbc: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xhg?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
        password: 1234
        druid: 
          initialSize: 1
          minIdle: 1
          maxActive: 10
          maxWait: 10000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: false
  configuration:
    #oracle数据库必须配置 jdbc-type-for-null
    jdbc-type-for-null: 'null'
    cache-enabled: false
    map-underscore-to-camel-case: true

